# Fail2Ban action: Cloudflare Universal (IPv4 + IPv6)
#
# Akan menambahkan block rule ke Cloudflare Firewall
# untuk IP (IPv4 atau IPv6) yang terdeteksi.

[Definition]
actionstart =
actionstop =
actioncheck =

actionban = echo "$(date '+%%Y-%%m-%%d %%H:%%M:%%S') [Fail2Ban Cloudflare] Banning <ip>" >> /var/log/fail2ban/cloudflare.log; \
    if echo "<ip>" | grep -q ":"; then \
        target="ip6"; \
    else \
        target="ip"; \
    fi; \
    curl -s -X POST \
    -H "X-Auth-Email: <cfuser>" \
    -H "X-Auth-Key: <cfapikey>" \
    -H "Content-Type: application/json" \
    -d "{\"mode\":\"block\",\"configuration\":{\"target\":\"$target\",\"value\":\"<ip>\"},\"notes\":\"Fail2Ban <name>\"}" \
    "https://api.cloudflare.com/client/v4/user/firewall/access_rules/rules" >> /var/log/fail2ban-cloudflare.log  2>&1

actionunban = echo "$(date '+%%Y-%%m-%%d %%H:%%M:%%S') [Fail2Ban Cloudflare] Unbanning <ip>" >> /var/log/fail2ban/cloudflare.log; \
    if echo "<ip>" | grep -q ":"; then \
        target="ip6"; \
    else \
        target="ip"; \
    fi; \
    curl -s -X DELETE \
    -H "X-Auth-Email: <cfuser>" \
    -H "X-Auth-Key: <cfapikey>" \
    -H "Content-Type: application/json" \
    "https://api.cloudflare.com/client/v4/user/firewall/access_rules/rules?configuration.target=$target&configuration.value=<ip>" \
    >> /var/log/fail2ban-cloudflare.log  2>&1

[Init]
cfuser   = YOUREMAL@EXAMPLE.COM
cfapikey = YOURTOKENCLOUDFLARE
