# Fail2Ban filter for Apache Guacamole
#
# Log contoh:
# 23:27:05.294 [http-nio-8080-exec-1] WARN  o.a.g.r.auth.AuthenticationService - Authentication attempt from 192.168.55.8 for user "aaaavb" failed.
# 23:27:39.164 [http-nio-8080-exec-3] WARN  o.a.g.r.auth.AuthenticationService - Authentication attempt from 2404:c0:5c10::c68a:1f15 for user "a" failed.

[Definition]
failregex = ^.*Authentication attempt from <HOST> for user .* failed\.$

ignoreregex =