[Definition]

# Failregex untuk menangkap login gagal Guacamole
# Menangkap IPv4, IPv6, atau kombinasi [IPv6, IPv4]
failregex = ^.*WARN\s+o\.a\.g\.r\.auth\.AuthenticationService\s+-\s+Authentication attempt from (\[[0-9a-fA-F:,. ]+\]|<HOST>) for user "[^"]*" failed\.$

ignoreregex =

# Hanya 1 baris per event
maxlines = 1

# Sesuaikan datepattern dengan format log catalina.out
datepattern = ^%H:%M:%S.%f