[DEFAULT]
destemail = fachmi@thismydomains.com
sender = noreply@thismydomains.com.com
action = %(action_mwl)s

ignoreip = 127.0.0.1 192.168.55.0/28 192.168.60.0/28
banaction = cloudflare telegram

[sshd]
backend = systemd
enabled = true